require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"

require "user.alpha"
require "user.bufferline"
require "user.cmp"
require "user.gitsigns"
require "user.indentline"
require "user.lsp"
require "user.lualine"
require "user.nvim-tree"
require "user.telescope"
require "user.treesitter"
require "user.whichkey"
