# set-option -a terminal-features 'xterm-256color:RGB'
set-option -a terminal-features '*:RGB'

set-option -g base-index 1
set-option -g pane-base-index 1

bind \\ move-window -r

set-option -g mouse off

set-option -g history-limit 100000

set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -s focus-events on
set-option -s escape-time 0

DARK_AMBER="#ff8f40"
AMBER="#ffb454"

FG=${DARK_AMBER}
BG="#0f131a"

set-option -g status-position bottom
set-option -g status-style bg=${BG},fg=${FG}

set-option -g window-status-format "\
 \
#I\
:\
#W\
 \
"

set-option -g window-status-current-format "\
#[bg=${DARK_AMBER}] \
#[bg=${DARK_AMBER},fg=#{BG}]#I\
#[fg=${BG}]:\
#[fg=${BG}]#W\
#[bg=${DARK_AMBER}] \
"

set-option -g window-status-separator ""
