# set-option -a terminal-features 'xterm-256color:RGB'
set-option -a terminal-features '*:RGB'

set-option -g base-index 1
set-option -g pane-base-index 1

bind \\ move-window -r

set-option -g mouse off

set-option -g history-limit 100000

set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -s focus-events on
set-option -s escape-time 0

set-option -g status-interval 5

bind-key C-p previous-window
bind-key C-n next-window

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @ukiyo-theme "kanagawa/wave"
set -g @ukiyo-color-bg-pane "sumi_ink_1"
set -g @ukiyo-plugins " "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
